[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#176B87"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#162B3D"
font = "sans serif"
